version: '3.1'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: .docker/entrypoint.sh
    container_name: sales-api-app
    ports:
      - '3333:3333'
    volumes:
      - .:/usr/src/sales-api
    depends_on:
      - database
    command: sh -c "npm install && npm run dev"

  database:
    image: postgres:alpine
    container_name: sales-api-database
    restart: always
    environment:
      POSTGRES_DB: 'sales'
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: '123'
    ports:
      - '5432:5432'

  pgadmin:
    image: adminer
    container_name: sales-api-adminer
    restart: always
    ports:
      - 8080:8080
